# Upptime Response Time Workflow
name: Response Time CI
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
jobs:
  update-response-time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update response time
        uses: upptime/uptime-monitor@master
        with:
          command: response-time
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
