# Upptime Site Workflow
name: Site CI
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
  push:
    branches:
      - master
      - 001-use-upptime-https
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build status page
        uses: upptime/uptime-monitor@master
        with:
          command: site
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
