# Upptime Site Workflow
name: Site CI
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
  push:
    branches:
      - master
      - 001-use-upptime-https
jobs:
  build-site:
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to push to gh-pages
    steps:
      - uses: actions/checkout@v3
      - name: Build status page
        uses: upptime/uptime-monitor@master
        with:
          command: site
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: Deploy to GitHub Pages
        run: |
          cd site/__sapper__/export
          git init
          git config user.name "ebashmakov"
          git config user.email "ebashmakov@users.noreply.github.com"
          echo "upptime.bandlab.com" > CNAME
          git add -A
          git commit -m "Deploy status page"
          git push -f https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:gh-pages
